import { ItemReport, PotentialMatch, Claim, UserNotification } from '../types';

export const SAMPLE_CAMPUS_LOCATIONS = [
  'Main Library - 1st Floor Cafe',
  'Main Library - 2nd Floor Quiet Study',
  'Student Center - Ground Floor Lounge',
  'Student Center - Food Court',
  'Science & Engineering Quad',
  'Math Hall - Room 204',
  'Recreation & Wellness Center (Gym)',
  'West Campus Residence Lawn',
  'North Dining Pavilion',
  'Performing Arts Center Lobby',
  'Campus Bookstore & Post Office',
  'University Shuttle Bus Stop',
];

export const SAMPLE_ITEMS: ItemReport[] = [
  {
    id: 'item-1-lost-hydroflask',
    ownerId: 'demo-user-alex',
    reporterName: 'Alex Rivera',
    reporterEmail: 'alex.rivera@campus.edu',
    type: 'lost',
    title: 'Midnight Blue Hydro Flask (32oz)',
    category: 'Bottles & Containers',
    description: 'Dark blue wide-mouth Hydro Flask with a flex cap. Has an Outing Club sticker and a national parks sticker on the side.',
    location: 'Science & Engineering Quad',
    date: '2026-09-10',
    approximateTime: '2:15 PM',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    status: 'potential_match',
    privateDetails: 'Small dent on the bottom rim from dropping it on concrete last semester, and an initials sticker "AR" hidden under the boot.',
    createdAt: '2026-09-10T14:30:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'item-2-found-hydroflask',
    ownerId: 'demo-user-sam',
    reporterName: 'Sam Chen',
    reporterEmail: 'sam.chen@campus.edu',
    type: 'found',
    title: 'Navy Blue Insulated Water Bottle',
    category: 'Bottles & Containers',
    description: 'Found a 32oz dark blue vacuum bottle on the table near the entrance. Decorated with several outdoor stickers.',
    location: 'Main Library - 1st Floor Cafe',
    date: '2026-09-10',
    approximateTime: '4:45 PM',
    imageUrl: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?auto=format&fit=crop&w=800&q=80',
    turnInLocation: 'Library Circulation & Info Desk',
    status: 'potential_match',
    privateDetails: 'Bottom has noticeable dent and silicone boot with initial AR underneath.',
    createdAt: '2026-09-10T17:00:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
  },
  {
    id: 'item-3-lost-sony-headphones',
    ownerId: 'demo-user-alex',
    reporterName: 'Alex Rivera',
    reporterEmail: 'alex.rivera@campus.edu',
    type: 'lost',
    title: 'Sony WH-1000XM4 Noise-Canceling Headphones',
    category: 'Audio & Headphones',
    description: 'Matte black over-ear headphones inside their black zip travel case. Left on a low couch while studying between lectures.',
    location: 'Student Center - Ground Floor Lounge',
    date: '2026-09-11',
    approximateTime: '11:00 AM',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    status: 'potential_match',
    privateDetails: 'Slight diagonal scratch along the left hinge bracket. Auxiliary headphone cable is folded in the mesh net inside the case.',
    createdAt: '2026-09-11T12:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'item-4-found-sony-headphones',
    ownerId: 'demo-user-taylor',
    reporterName: 'Campus Security Desk (Taylor)',
    reporterEmail: 'security-lostfound@campus.edu',
    type: 'found',
    title: 'Black Sony Wireless Over-Ear Headphones',
    category: 'Audio & Headphones',
    description: 'Turned into security. Black premium headphones stored in protective zippered pouch.',
    location: 'Student Center - Ground Floor Lounge',
    date: '2026-09-11',
    approximateTime: '1:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    turnInLocation: 'Student Union Security Central Office - Room 102',
    status: 'potential_match',
    privateDetails: 'Left hinge has silver scratch; contains audio jack cable inside.',
    createdAt: '2026-09-11T13:45:00Z',
    updatedAt: '2026-09-11T13:45:00Z',
  },
  {
    id: 'item-5-lost-calculator',
    ownerId: 'demo-user-morgan',
    reporterName: 'Morgan Patel',
    reporterEmail: 'morgan.p@campus.edu',
    type: 'lost',
    title: 'TI-84 Plus CE Graphing Calculator (Mint Green)',
    category: 'Electronics',
    description: 'Mint green graphing calculator with slide case. Left on desk row 3 after Calc III midterm exam.',
    location: 'Math Hall - Room 204',
    date: '2026-09-12',
    approximateTime: '10:15 AM',
    imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    status: 'active',
    privateDetails: 'Inside the slide cover there is a sticker of a Shiba Inu with sunglasses.',
    createdAt: '2026-09-12T10:45:00Z',
    updatedAt: '2026-09-12T10:45:00Z',
  },
  {
    id: 'item-6-found-airpods',
    ownerId: 'demo-user-sam',
    reporterName: 'Sam Chen',
    reporterEmail: 'sam.chen@campus.edu',
    type: 'found',
    title: 'AirPods Pro 2 in Lavender Silicone Case',
    category: 'Audio & Headphones',
    description: 'Found on the cup holder shelf of elliptical machine #4 in the upper cardio deck.',
    location: 'Recreation & Wellness Center (Gym)',
    date: '2026-09-12',
    approximateTime: '8:30 AM',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    turnInLocation: 'Gym Front Reception Desk',
    status: 'active',
    privateDetails: 'The silicone case has an enamel astronaut keychain charm attached to the lanyard loop.',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-12T09:00:00Z',
  },
  {
    id: 'item-7-lost-keys',
    ownerId: 'demo-user-jordan',
    reporterName: 'Jordan Lee',
    reporterEmail: 'jordan.lee@campus.edu',
    type: 'lost',
    title: 'Dorm Keys on Yellow Mountain Lanyard',
    category: 'Keys',
    description: 'Keyring with 2 silver dorm keys, a gold mailbox key, and a solid brass bottle opener.',
    location: 'West Campus Residence Lawn',
    date: '2026-09-09',
    approximateTime: '7:40 PM',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=800&q=80',
    status: 'active',
    privateDetails: 'The dorm room key has a blue rubber cap with "W4" marked in permanent marker.',
    createdAt: '2026-09-09T20:00:00Z',
    updatedAt: '2026-09-09T20:00:00Z',
  },
  {
    id: 'item-8-returned-applepencil',
    ownerId: 'demo-user-alex',
    reporterName: 'Alex Rivera',
    reporterEmail: 'alex.rivera@campus.edu',
    type: 'lost',
    title: 'Apple Pencil 2nd Generation',
    category: 'Electronics',
    description: 'White stylus pencil with silicone grip. Reunited with owner via ReFound!',
    location: 'Performing Arts Center Lobby',
    date: '2026-09-08',
    approximateTime: '3:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    status: 'returned',
    privateDetails: 'Laser engraved with "A. Rivera 2024" on the magnetic flat side.',
    createdAt: '2026-09-08T15:30:00Z',
    updatedAt: '2026-09-09T11:00:00Z',
  },
];

export const SAMPLE_MATCHES: PotentialMatch[] = [
  {
    id: 'match-1',
    lostItemId: 'item-1-lost-hydroflask',
    foundItemId: 'item-2-found-hydroflask',
    lostItemTitle: 'Midnight Blue Hydro Flask (32oz)',
    foundItemTitle: 'Navy Blue Insulated Water Bottle',
    lostItemOwnerId: 'demo-user-alex',
    foundItemOwnerId: 'demo-user-sam',
    confidenceScore: 89,
    matchTier: 'High',
    matchReasons: 'Both items are 32oz dark/navy blue insulated water bottles with outdoor stickers. The timeline is consistent (lost at 2:15 PM, found at 4:45 PM on the same date) and locations are adjacent campus buildings.',
    keySimilarities: ['Same 32oz size & navy/dark blue color', 'Both feature outdoor club stickers', 'Found 2.5 hours after lost report', 'Nearby campus locations (Quad & Library)'],
    keyDifferences: ['Lost described as flex cap; found specifies bottle only'],
    status: 'suggested',
    createdAt: '2026-09-10T17:05:00Z',
  },
  {
    id: 'match-2',
    lostItemId: 'item-3-lost-sony-headphones',
    foundItemId: 'item-4-found-sony-headphones',
    lostItemTitle: 'Sony WH-1000XM4 Noise-Canceling Headphones',
    foundItemTitle: 'Black Sony Wireless Over-Ear Headphones',
    lostItemOwnerId: 'demo-user-alex',
    foundItemOwnerId: 'demo-user-taylor',
    confidenceScore: 94,
    matchTier: 'High',
    matchReasons: 'Exact brand (Sony), over-ear style, black color, and both in protective travel zip cases. Same building location (Student Center Ground Floor Lounge) reported within 2.5 hours.',
    keySimilarities: ['Exact brand: Sony Over-Ear', 'Both inside black zip case', 'Exact same building: Student Center Lounge', 'Found shortly after lost report on 2026-09-11'],
    keyDifferences: ['Finder report did not specify exact XM4 model number'],
    status: 'suggested',
    createdAt: '2026-09-11T13:50:00Z',
  },
];

export const SAMPLE_CLAIMS: Claim[] = [
  {
    id: 'claim-1',
    itemId: 'item-2-found-hydroflask',
    itemTitle: 'Navy Blue Insulated Water Bottle',
    itemOwnerId: 'demo-user-sam',
    claimantId: 'demo-user-alex',
    claimantName: 'Alex Rivera',
    claimantEmail: 'alex.rivera@campus.edu',
    claimantPhone: '(555) 234-8901',
    identifyingAnswers: 'The bottle has a dent along the bottom edge where it dropped, and underneath the silicone boot are the initials "AR" written in black sharpie. Also has a Yosemite half-dome sticker on the opposite side.',
    status: 'pending',
    createdAt: '2026-09-10T18:15:00Z',
    updatedAt: '2026-09-10T18:15:00Z',
  },
];

export const SAMPLE_NOTIFICATIONS: UserNotification[] = [
  {
    id: 'notif-1',
    userId: 'demo-user-alex',
    title: 'Possible Match Found!',
    message: 'Gemini detected an 89% match between your lost Midnight Blue Hydro Flask and a found bottle turned in at the Library.',
    type: 'match_found',
    relatedItemId: 'item-1-lost-hydroflask',
    relatedMatchId: 'match-1',
    isRead: false,
    createdAt: '2026-09-10T17:05:00Z',
  },
  {
    id: 'notif-2',
    userId: 'demo-user-alex',
    title: 'High Confidence Match: Sony Headphones',
    message: 'Campus Security logged black Sony headphones at the Student Center that match your report with 94% similarity.',
    type: 'match_found',
    relatedItemId: 'item-3-lost-sony-headphones',
    relatedMatchId: 'match-2',
    isRead: false,
    createdAt: '2026-09-11T13:50:00Z',
  },
  {
    id: 'notif-3',
    userId: 'demo-user-sam',
    title: 'New Claim Received',
    message: 'Alex Rivera filed a verification claim for the Navy Blue Water Bottle you reported finding.',
    type: 'claim_received',
    relatedItemId: 'item-2-found-hydroflask',
    relatedClaimId: 'claim-1',
    isRead: false,
    createdAt: '2026-09-10T18:15:00Z',
  },
];
